branches:
    exclude:
        - gh-pages
matrix:
    TEST:
        - audit
        - conventions
        - examples
        - visual-regression

pipeline:
    audit:
        image: 'node:dubnium'
        commands:
            - 'yarn install --frozen-lockfile'
            - 'yarn audit'
        when:
            matrix: {TEST: audit}

    conventions:
        image: 'node:dubnium'
        commands:
            - 'yarn install --frozen-lockfile'
            - 'yarn test:coding-conventions'
        when:
            matrix: {TEST: conventions}

    examples:
        image: 'node:dubnium'
        commands:
            - 'yarn install --frozen-lockfile'
            - 'cd examples/webpack4 && yarn build --display=errors-only'
            - 'cd ../webpack4-eu && yarn build --display=errors-only'
        when:
            matrix: {TEST: examples}

    visual-regression:
        image: hivelocityinc/docker-node-chromium
        shm_size: 1g
        commands:
            - 'yarn install --frozen-lockfile'
            - 'yarn test:ec-build'
            - 'yarn test:ec-visual'
        when:
            event: [push]
            matrix: {TEST: visual-regression}
