branches:
  exclude:
    - gh-pages
matrix:
  TEST:
    - audit
    - conventions
    - examples
    - visual-regression

pipeline:
  install:
    image: 'node:dubnium'
    commands:
      - 'yarn install --frozen-lockfile'

  audit:
    image: 'node:dubnium'
    commands:
      - 'yarn audit'
    when:
      matrix: { TEST: audit }

  conventions:
    image: 'node:dubnium'
    commands:
      - 'yarn test:coding-conventions'
    when:
      matrix: { TEST: conventions }

  examples:
    image: 'node:dubnium'
    commands:
      - 'cd examples/webpack4 && yarn build --display=errors-only'
      - 'cd ../webpack4-eu && yarn build --display=errors-only'
    when:
      matrix: { TEST: examples }

  s3:
    image: kalinchernev/node-dubnium-aws-cli
    secrets: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_DEFAULT_REGION]
    commands:
      - 'yarn install --frozen-lockfile'
      - 'yarn dist:storybook'
      - if [ -d "./dist" ] ; then
        cd ./dist/storybook ;
        aws configure set default.s3.max_concurrent_requests 20 ;
        aws s3 cp --recursive --quiet . s3://inno-ecl/build/${DRONE_BUILD_NUMBER}/ ;
        echo "Transfer complete" ;
        fi

    when:
      event: [push]
      matrix: { TEST: visual-regression }

  visual-regression:
    image: 'node:dubnium'
    secrets: [SAUCE_USERNAME, SAUCE_ACCESS_KEY]
    commands:
      - 'yarn test:visual:noexitonfail'
    when:
      event: [push]
      matrix: { TEST: visual-regression }
