[build]
  command = "yarn run dist"
  publish = "dist/website"

[build.environment]
  YARN_VERSION = "1.12.3"
  YARN_FLAGS = "--frozen-lockfile"

# v2 branch: only redirect
[context.v2]
  command = "echo 'Setting redirects...'"

[[redirects]]
  from = "https://v2--europa-component-library.netlify.com/*"
  to = "https://ec.europa.eu/component-library/:splat"
